### ISSUE TITLE
Add type object  in fields

### ISSUE THREAD

**Issue by prashanthvdckap** [measuredco/puck#226] opened 2023-11-14 07:36 UTC
Add type object  in fields so that we can have key pair fields

**Comment by chrisvxd** [comment] 2023-11-23 14:25
Thanks @prashanthvdckap. This is a duplicate of #79.

**Closed by chrisvxd** 2023-11-23 14:25 UTC

**Comment by chrisvxd** [comment] 2023-11-28 09:49
Hi @prashanthvdckap. This was delivered in #256 and should be available in `0.13.0-canary.b95050d`. Please let me know if that works for you.
