### ISSUE TITLE
Drag and Drop issue

### ISSUE THREAD

**Issue by htmldiz** [measuredco/puck#712] opened 2024-11-24 18:46 UTC
There is no way to change position of elements that already was used in render area.
Working example:
<img width="894" alt="image" src="https://github.com/user-attachments/assets/cfa7a6f2-9d22-43dc-b33a-0798275c4cea">
Not working example:
<img width="911" alt="image" src="https://github.com/user-attachments/assets/de7663b2-9a37-43f4-8fc5-8bbb1022cae3">

**Comment by ben-pr-p** [comment] 2024-11-25 15:28
I believe this is a duplicate of https://github.com/measuredco/puck/issues/123

The issue to implement a new engine is here https://github.com/measuredco/puck/issues/556

PR in progress is here, with heroic progress being made: https://github.com/measuredco/puck/pull/598

**Closed** 2024-12-01 20:45 UTC
