### ISSUE TITLE
DropZones don't work in Safari 17.2 or newer

### ISSUE THREAD

**Issue by goynang** [measuredco/puck#411] opened 2024-04-02 20:54 UTC
Hi, first off, thanks for the awesome project.

I've just upgraded to v0.14.0 and now also v0.14.1 and I've found that DropZones no longer work when using Safari. There are no errors, you just can't drop any elements into the zones. You can drop onto the root level of the page however.

You can see this on the demo site so it's simple to recreate (so long as you have access to Safari). It works fine in Chrome.

**Comment by chrisvxd** [comment] 2024-04-03 07:48
Thanks @goynang! I'm unable to reproduce this in Safari Version 17.1 (19616.2.9.11.7). Can you confirm which version you're running?


https://github.com/measuredco/puck/assets/985961/4db48fb8-9dd9-4fbb-96a5-b2b8f7fb4539

**Comment by goynang** [comment] 2024-04-03 17:20
Safari Version 17.2.1 (19617.1.17.11.12) on Sonoma 14.2.1. Video below (using your demo site).

https://github.com/measuredco/puck/assets/196103/4d50e15c-ec6e-4f7b-99b2-b9019b31d201

**Comment by chrisvxd** [comment] 2024-04-04 10:48
I've been able to replicate this on newer versions of Safari. I believe this is actually a change in how Safari 17.2 handles pointer-events.

They note "Since our last release, Safari greatly improved our implementation of Pointer and Mouse events" in their [release notes](https://webkit.org/blog/14787/webkit-features-in-safari-17-2/).

This behaviour relies on `pointer-event: all`, which is experimental and the behaviour likely changed. I'll have to explore patching this functionality.

**Comment by chrisvxd** [comment] 2024-04-04 13:04
Further to the above, this issue _only_ seems to manifest inside iframes, which is why it's occurring in 0.14 and not previously. Strange. I will continue to investigate...

**Comment by chrisvxd** [comment] 2024-04-04 13:25
I suspect this might be resolved in Safari 17.5, which just went into beta and has the following line in the [release notes](https://developer.apple.com/documentation/safari-release-notes/safari-17_5-release-notes)

> Fixed mousemove events in an iframe when the mouse is clicked from outside the iframe and then moves into it while the button is held down. (120540148) (FB13517196)

This sounds like what I'm experiencing during debugging - the event is not getting fired inside the iframe while the button is held down (aka dragging).

**Closed** 2024-04-06 17:11 UTC

**Comment by chrisvxd** [comment] 2024-04-06 17:12
Hi @goynang - I added a Safari 17.2, 17.3 and 17.4 compatibility mode in #421. It's not perfect, but it should serve as an adequate fallback until Safari 17.5 is released (which I'm _assuming_ fixes the issue).
