### ISSUE TITLE
Composable fields

### ISSUE THREAD

**Issue by xaviemirmon** [measuredco/puck#361] opened 2024-03-05 19:52 UTC
Now that Puck has some composability built in it'd be great to explore how we might be able to extend this to fields. I've run into a few instances with  custom fields where it requires quite a bit of work to get the styles to match pre-existing fields.  For example I have a field fields which ideally display  as a radio but require some changes to the underlying logic so I have to reference Puck classes which are prone to changes with each new version of Puck.  

Additionally, it would be useful to allow use of another frontend library e.g. Material, Mantine, etc. for the Puck UI so that we could style Puck's interface alongside a larger admin interface.

**Comment by chrisvxd** [comment] 2024-03-25 13:24
Hey @xaviemirmon - I think the first request is a duplicate of #365, and the second request can be achieved via [field overrides](https://puckeditor.com/docs/extending-puck/custom-interfaces#field-type-override-example). In future, it might also be possible to "theme" the fields via #139.

I'm going to close this, but feel free to comment if I have the wrong end of the stick.

**Closed by chrisvxd** 2024-03-25 13:24 UTC
