### ISSUE TITLE
Field groups or tabs

### ISSUE THREAD

**Issue by jperasmus** [measuredco/puck#314] opened 2023-12-24 13:09 UTC
Feature request:

Similar to how components can be categorised in the left side panel, it would be great if component fields can be grouped into either collapsible accordions or even tabs.

This is useful when you start to have many fields. In my case, I'm trying to allow users to set almost any CSS properties like: padding, margin, background (color, repeat, size, position), fontFamily, fontSize, fontStyle, fontWeight, lineHeight, lineClip, etc etc.

A possible configuration could look like this (analogous to how component categories are configured):

```tsx
export const Heading: ComponentConfig<HeadingProps> = {
  fields: {
    heading: {
      type: "text",
    },
    level: {
      type: "select",
      label: "Level (1-6)",
      options: [
        { label: "Heading 1", value: "1" },
        { label: "Heading 2", value: "2" },
        { label: "Heading 3", value: "3" },
        { label: "Heading 4", value: "4" },
        { label: "Heading 5", value: "5" },
        { label: "Heading 6", value: "6" },
      ],
    },
    textColor: {
      type: "custom",
      render: TextColorField,
    },
    backgroundColor: {
      type: "custom",
      render: BackgroundColorField,
    },
    fontFamily: {
      type: "custom",
      render: FontFamilyField,
    },
    fontSize: {
      type: "custom",
      render: FontSizeField,
    },
    fontStyle: {
      type: "custom",
      render: FontStyleField,
    },
    // ...more fields
  },
  fieldGroups: {
    main: {
      title: "Main",
      fields: ["heading", "level"],
    },
    typography: {
      title: "Typography",
      fields: ["fontFamily", "fontSize", "fontStyle"],
    },
    other: {
      title: "Other",
    },
  },
  defaultProps: {},
  render() {},
}
```

**Comment by jperasmus** [comment] 2023-12-27 13:30
I'm happy to contribute a PR if you're interested in this feature.

**Comment by chrisvxd** [comment] 2023-12-27 15:02
Thanks for the proposal @jperasmus! This looks like a duplicate of #64.

It might be worth bringing your proposal over to #64 so we can compare the different approaches.

**Closed by chrisvxd** 2023-12-27 15:02 UTC

**Comment by jperasmus** [comment] 2023-12-27 15:28
Ah, thanks. I didn't see that one. I'll comment on it.
