### ISSUE TITLE
Orderable outline/layers

### ISSUE THREAD

**Issue by jperasmus** [measuredco/puck#308] opened 2023-12-21 16:04 UTC
Feature request:

It would be great if the items in the `<Outline />` component were orderable via drag-and-drop. That way a user would be able to quickly move bigger blocks around without needing to do it in the preview frame.

Another smaller request is to show the top-level page in the Outline for easy selection.

**Comment by chrisvxd** [comment] 2023-12-21 17:09
Good request! Been on our radar for a while but has never been prioritised.

I think drag-and-drop between a given DropZone should be easy enough, but drag-and-drop between DropZones is more challenging. We could possibly phase the implementation.

**Comment by jperasmus** [comment] 2023-12-21 17:25
Also, you would want the items to respect the "allow" and "disallow" props on dropzones (if dropping inside a component).

**Comment by chrisvxd** [comment] 2024-03-25 13:34
Closing as duplicate of #126

**Closed by chrisvxd** 2024-03-25 13:34 UTC
Labels: type: feature, in triage
