### ISSUE TITLE
Type: radio not clickable in arrayFields

### ISSUE THREAD

**Issue by thopedam** [measuredco/puck#653] opened 2024-10-11 21:52 UTC
Radio Fields inside arrayFields are not clickable in puck 0.16.1

Might be related: https://github.com/measuredco/puck/pull/643

**Comment by joeyhotz** [comment] 2024-11-25 04:35
can confirm facing the same issue. will revert to just using a select for now

**Comment by chrisvxd** [comment] 2024-12-16 16:30
Ah this is a dupe of #723, which has been closed. Apologies for slow reaction to this one.

**Closed by chrisvxd** 2024-12-16 16:30 UTC
Labels: ready, type: bug 🐛
