### ISSUE TITLE
Pagination in fetchList

### ISSUE THREAD

**Issue by BR1G00** [measuredco/puck#596] opened 2024-09-03 13:49 UTC
It would be nice if in fetchList mode we could paginate the result, but not only client side.
Currently there is no valid way to do it, one of the most annoying obstacles is that there is no possibility to disable the cache, because for example if I do something in the fetchList function, when puck returns me the cached result, the function does not fire and I have lost the logic of the function.

**Comment by chrisvxd** [comment] 2024-11-04 09:40
Realised this is duplicate of #262

**Closed by chrisvxd** 2024-11-04 09:40 UTC
Labels: type: feature, in triage
